name: Ubuntu RDP with Ngrok

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install XRDP
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Install Ngrok
      run: |
        mkdir -p $HOME/ngrok
        cd $HOME/ngrok
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start Ngrok Tunnel
      run: |
        cd $HOME/ngrok
        ./ngrok tcp 3389 &

    - name: Set up XRDP session
      run: |
        sleep 10 # Wait for Ngrok to start
        DISPLAY=:0 sudo xrdp

    - name: Display Ngrok Tunnel URL
      run: |
        sleep 20 # Wait for XRDP to start
        curl http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
